# Advanced Indexing

In [1]:
import numpy as np 

## Fancy Indexing

In [2]:
arr = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
index_list = np.array([0, 4, 1, 4])

selection = arr[index_list]
print(f"Selection: {selection}")

Selection: ['a' 'e' 'b' 'e']


In [7]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 2, 1])
col_indices = np.array([0, 1, 2])

selection_pairs = matrix[row_indices, col_indices]
print(f"Selection Pairs: {selection_pairs}")

Selection Pairs: [10 80 60]


## Boolean Indexing

Boolean indexing is powerful because it allows to filter data based on complex condition.

#### Mask Creation 

Mechanism: You create a boolean array (mask) of the same shape as the data array, where True indicates the element to keep.

Goal: Select all elements that satisfy a condition, often used for data cleaning or feature engineering.

In [ ]:
data = np.random.randint(0, 100, size=(4,4))
print(f"Original Data:\n {data}")

Original Data:
 [[82 19 78 23]
 [27 61 51 73]
 [25 30 92 17]
 [ 0 42 24 62]]


In [ ]:
# Create a boolean mask: True for values greater than 50
mask = data > 60
print(f"\n Boolean Mask:\n {mask}")



 Boolean Mask:
 [[ True False  True False]
 [False  True False  True]
 [False False  True False]
 [False False False  True]]


In [15]:
# Apply the mask
high_values = data[mask]
print(f"\n High Values (1D Object): {high_values}")



 High Values (1D Object): [82 78 61 73 92 62]
