## Numpy Basics and Fundamentals
Learn about nummpy in python with chai aur code

In [3]:
import numpy as np

### Creating array from lists

In [7]:
arr_1d = np.array([1,2,3,4,4,5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,4,5]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 4 5]
2D Array: [[1 2 3]
 [4 4 5]]


### List vs Numpy Array

In [9]:
py_list = [1,2,3]
print("Python List Multiplication:", py_list * 2)

# element wise multiplcation of numpy array
np_array = np.array([1,2,3])
print("Python Array Multiplication:", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Array Operation Time", time.time() - start)

Python List Multiplication: [1, 2, 3, 1, 2, 3]
Python Array Multiplication: [2 4 6]

 List Operation Time 0.04700446128845215

 Numpy Array Operation Time 0.006596803665161133


### Creating Array from Scratch

In [17]:
# zeros array
zeros = np.zeros((3,4))
print("Zeros: \n", zeros)

# ones array
ones = np.ones((2,3))
print("ones: \n", ones)

# full array 
full = np.full((2,2), 7)
print("Full: \n", full)

# random
random = np.random.random((3,3))
print("random: \n", random)

# creating a sequence
sequence = np.arange(0, 10, 2)
print("Sequence: \n", sequence)

Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full: 
 [[7 7]
 [7 7]]
random: 
 [[0.11068585 0.08956919 0.5540895 ]
 [0.250707   0.3695976  0.69983751]
 [0.97095064 0.02801171 0.54305331]]
Sequence: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("VECTOR: \n", vector)

# 2D or Matrix 
matrix = np.array([[1,2,3],
                   [1,2,3]])
print("MATRIX: \n", matrix)

# Tensors : multi-dimensional array
tensor = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("Tensor: \n", tensor)
# Plants the use of heavy calculation
# TENSROFLOW, PYTORCH, TPU : Tensor Processing Unit

VECTOR: 
 [1 2 3]
MATRIX: 
 [[1 2 3]
 [1 2 3]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])

# Although, it won't raise an error, but numpy array operations,
# are optimized as they're suppossed to have similar data_types!!! 
print("Shape of Array: ", arr.shape)
print("Dimension of Array: ", arr.ndim)
print("Size of Array: ", arr.size)
print("Data type of Array: ", arr.dtype)

Shape of Array:  (2, 3)
Dimension of Array:  2
Size of Array:  6
Data type of Array:  int64


### Array Reshaping

In [42]:
arr = np.arange(12)
print("Original Array:",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array: \n", reshaped)

# Flattened (returns copy, instead of view)
flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)

# Ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Ravelled Array: ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose: \n", transpose)

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravelled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
