##  Numpy Array Operations

In [1]:
import numpy as np

### Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[2:7:2])
print("Negative Indexing", arr[-3]) # Reverse Order

Basic Slicing [3 4 5 6 7]
With Step [3 5 7]
Negative Indexing 8


In [ ]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element", arr_2d[1, 2]) # (Rows, Column)
print("Entire Row", arr_2d[1])
print("Entire Column", arr_2d[:,1])


Specific Element 6
Entire Row [4 5 6]
Entire Column [2 5 8]


### Sorting

In [ ]:
unsorted = np.array([3,1,4,5,2,7,6])

print("Unsorted Array: ", unsorted)
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Unsorted 2d array: \n", arr_2d_unsorted)
# Column wise sorting of 2d array  
print("Sorted 2d Array by Column: \n", np.sort(arr_2d_unsorted, axis = 0)) # (arr, axis)
# axis 1 => sorting but at individual row level only
print("Sorted 2d Array by Row: \n", np.sort(arr_2d_unsorted, axis = 1))


Unsorted Array:  [3 1 4 5 2 7 6]
Sorted Array:  [1 2 3 4 5 6 7]
Unsorted 2d array: 
 [[3 1]
 [1 2]
 [2 3]]
Sorted 2d Array by Column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2d Array by Row: 
 [[1 3]
 [1 2]
 [2 3]]


### Filter

In [20]:
numbers = np.arange(11)
print("Numbers: ", numbers)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ",even_numbers)

Numbers:  [ 0  1  2  3  4  5  6  7  8  9 10]
Even Numbers:  [ 0  2  4  6  8 10]


#### Filter with Mask

In [ ]:
# mask is a term in numpy, and evaluating expression.
# Eg: [numbers % 2 == 0]
mask = numbers > 5 
# Created and stored an expression, as a mask
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


#### Fancy Indexing vs np.where()

In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

# np.where() is used to create a conditional where clause

where_result =  np.where(numbers > 5) # where the condition is true, store in where_result
print(" NP Where", numbers[where_result])

[0 2 4]
(array([ 6,  7,  8,  9, 10]),)
 NP Where [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
# np.where(condition, x, y)
print(condition_array)

[ 0  1  2  3  4  5  6  7  8  9 10]
